### ISSUE TITLE
Create rooms by category

### ISSUE THREAD

**Issue by felipebaltazar** [felipebaltazar/Xartic#1]
## Description

Create game rooms with many kind of categories

## ToDo list

- [ ] Allow to create rooms
- [ ] List rooms from API controllers
- [ ] Create many files (json) with words for each room category
- [ ] List rooms on App and Web applications
