### ISSUE TITLE
Allow draw from app

### ISSUE THREAD

**Issue by felipebaltazar** [felipebaltazar/Xartic#2]
## Description

Allow users draw from app mobile

## ToDo list

- [ ] Create a possibility to play turns 
- [ ] Change the current word for each game turn
- [ ] Follow the player's list order for the turns
- [ ] Intercept touch on Skia Canvas and dispatch draw events when allowed
- [ ] Create button to clear draw from app
- [ ] Hide chat when app is drawing
