### ISSUE TITLE
Allow user change profile pic (web/app)

### ISSUE THREAD

**Issue by felipebaltazar** [felipebaltazar/Xartic#4]
## Description

Allow users change profile picture

## ToDo list

- [ ] Load predefined profile avatar list
- [ ] Load from disk/storage
- [ ] Store in preferences
